name: 构建发行

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备GO环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: 构建软件
        run: go build -o k8s-image        
      - name: 发布软件
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release: ${{ github.ref }}:
            - Added feature A
            - Fixed bug B
          draft: false
          prerelease: false
      - name: 上传二进制文件
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./k8s-image
          asset_name: k8s-image
          asset_content_type: application/octet-stream
