- name: 创建GitHub Release
  id: create_release
  uses: actions/create-release@latest
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: v0.2.4
    release_name: v0.2.4
    body: 发布的内容
    draft: false
    prerelease: false
